# Drop and remove duplicates

In [1]:
import pandas as pd

In [6]:
data={'A':["TeamA","TeamB","TeamB","TeamC","TeamA"],
      'B':[50,40,40,30,50],
      'C':[True,False,False,False,True]}

In [7]:
df=pd.DataFrame(data)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [8]:
df.duplicated() #compares the entire rows

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [10]:
df.duplicated(keep='first') #checks from the top

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [14]:
df.duplicated(keep='last') #checks from the bottom

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [17]:
df.duplicated(keep=False) #gives true for all the duplicates

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [18]:
df.drop_duplicates()

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [19]:
df.drop_duplicates(keep="first")

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [20]:
df.drop_duplicates(keep="last")

       A   B      C
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [21]:
df.drop_duplicates(keep=False)

       A   B      C
3  TeamC  30  False

In [25]:
df.drop_duplicates(keep='first',inplace=True)

In [24]:
df.reset_index(drop=True)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [26]:
df=pd.read_csv('auto-mpg.csv')
pd.crosstab(df['cylinders'],df['model year'],rownames=['cylinders'],colnames=['model year'],margins=True) #cross tabulation

model year  70  71  72  73  74  75  76  77  78  79  80  81  82  All
cylinders
3            0   0   1   1   0   0   0   1   0   0   1   0   0    4
4            7  13  14  11  15  12  15  14  17  12  25  21  28  204
5            0   0   0   0   0   0   0   0   1   1   1   0   0    3
6            4   8   0   8   7  12  10   5  12   6   2   7   3   84
8           18   7  13  20   5   6   9   8   6  10   0   1   0  103
All         29  28  28  40  27  30  34  28  36  29  29  29  31  398

### sort_values()

In [42]:
data={'Name':['Alice','Bob','charlie','David'],
     'Score':[88,92,95,90]}
df=pd.DataFrame(data)
df

      Name  Score
0    Alice     88
1      Bob     92
2  charlie     95
3    David     90

In [43]:
sorted_df=df.sort_values(by='Score')
sorted_df

      Name  Score
0    Alice     88
3    David     90
1      Bob     92
2  charlie     95

In [44]:
sorted_df=df.sort_values(by='Score',ascending=False)
sorted_df

      Name  Score
2  charlie     95
1      Bob     92
3    David     90
0    Alice     88

In [45]:
df.sort_index(ascending=False)

      Name  Score
3    David     90
2  charlie     95
1      Bob     92
0    Alice     88

In [46]:
df.set_index('Name',inplace=True)

In [47]:
df

         Score
Name
Alice       88
Bob         92
charlie     95
David       90

In [48]:
df.sort_index(ascending=True)

         Score
Name
Alice       88
Bob         92
David       90
charlie     95

### apply()

In [50]:
s=pd.Series([35,67,90,45])
def pass_fail(x):
    return "pass" if x>=50 else "Fail"
result =s.apply(pass_fail)
print(result)

0    Fail
1    pass
2    pass
3    Fail
dtype: object

In [62]:
df=pd.DataFrame({"Physics":[60,70,80],
                  "Chemistry":[65,75,85],
                  "Maths":[70,80,90]})
df

   Physics  Chemistry  Maths
0       60         65     70
1       70         75     80
2       80         85     90

In [63]:
result=df.apply(sum) #row wise addition
print(result)

Physics      210
Chemistry    225
Maths        240
dtype: int64

In [64]:
result=df.apply(sum,axis=1) #column wise addition
print(result)

0    195
1    225
2    255
dtype: int64

In [65]:
df=pd.DataFrame({"Physics":[60,70,80],
                  "Chemistry":[65,75,85],
                  "Maths":[70,80,90]})
result=df.apply(lambda x: x.mean())
print(result)

Physics      70.0
Chemistry    75.0
Maths        80.0
dtype: float64

In [66]:
df['total']=df1.apply(lambda x:x.sum(),axis=1)
df

   Physics  Chemistry  Maths  total
0       60         65     70    195
1       70         75     80    225
2       80         85     90    255

In [67]:
def grade(total):
    if total>=250:
        return 'A'
    elif total>=200:
        return 'B'
    else:
        return 'C'

In [69]:
df['Grade']=df['total'].apply(grade)
df

   Physics  Chemistry  Maths  total Grade
0       60         65     70    195     C
1       70         75     80    225     B
2       80         85     90    255     A

### result_type()

In [73]:
df=pd.DataFrame({'width':[1,2],'height':[3,4]})
def get_stats(row):
    return[row['width']* row['height'],2*(row['width']+row['height'])]
df

   width  height
0      1       3
1      2       4

In [77]:
df.apply(get_stats,axis=1,result_type='expand')

   0   1
0  3   8
1  8  12

In [75]:
df.apply(get_stats,axis=1,result_type='broadcast')

   width  height
0      3       8
1      8      12

In [78]:
df.apply(get_stats,axis=1,result_type='reduce')

0     [3, 8]
1    [8, 12]
dtype: object

### args and kwargs parameters

In [80]:
def add_values(x,y,z):
    return x + y + z
df=pd.DataFrame({'A':[1,2],'B':[10,20]})
df=df.apply(add_values,args=(1,2))
print(df)

   A   B
0  4  13
1  5  23

In [81]:
#kwargs = Keyword arguements
def multiply_by_m(x,m):
    return x*m
df=pd.DataFrame({'A':[1,2],'B':[10,20]})
df=df.apply(multiply_by_m,m=10)
print(df)

    A    B
0  10  100
1  20  200

### astype() function

In [83]:
df=pd.DataFrame({'A':['1','2','3'],'B':['4','5','6']})
print(df.dtypes)

A    object
B    object
dtype: object

In [85]:
df['A']=df['A'].astype(int)
print(df.dtypes)

A     int32
B    object
dtype: object

### replace() function

In [88]:
df1=pd.DataFrame({"marks":[80,85,0,90],
                  "Attendance":[75,80,0,85],
                  "grade":["A","B","F","A"]})
print(df1)
result=df1.replace([80,75],[90,80])
print(result)

   marks  Attendance grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     A
   marks  Attendance grade
0     90          80     A
1     85          90     B
2      0           0     F
3     90          85     A

In [89]:
df1=pd.DataFrame({"marks":[80,85,0,90],
                  "Attendance":[75,80,0,85],
                  "grade":["A","B","F","A"]})
print(df1)
result=df1.replace({80:75,90:80})
print(result)

   marks  Attendance grade
0     80          75     A
1     85          80     B
2      0           0     F
3     90          85     A
   marks  Attendance grade
0     75          75     A
1     85          75     B
2      0           0     F
3     80          85     A

In [91]:
df1["marks"]=df1["marks"].replace(0,50)
df1

   marks  Attendance grade
0     80          75     A
1     85          80     B
2     50           0     F
3     90          85     A

In [92]:
df1["Attendance"]=df1["Attendance"].replace(0,60)
df1

   marks  Attendance grade
0     80          75     A
1     85          80     B
2     50          60     F
3     90          85     A

### concate()

In [95]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'C':[7,8]})
result=pd.concat([df1,df2],axis=0)
result

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

In [96]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'C':[7,8]})
result=pd.concat([df1,df2],axis=1)
result

   A  B  A  C
0  1  3  5  7
1  2  4  6  8

In [97]:
pd.concat([df1,df2],join="inner") #only keeps overlap

   A
0  1
1  2
0  5
1  6

In [98]:
pd.concat([df1,df2],join="inner",ignore_index=True) #resets the index to 0,1,2,....

   A
0  1
1  2
2  5
3  6

In [101]:
#sorts columns/index if they don't align
df1=pd.DataFrame({'E':[1,2],'B':[3,4]})
df2=pd.DataFrame({'C':[5,6],'D':[7,8]})
result=pd.concat([df1,df2],sort=False,axis=1)
result

   E  B  C  D
0  1  3  5  7
1  2  4  6  8

In [100]:
df1=pd.DataFrame({'A':[1,2],'B':[3,4]})
df2=pd.DataFrame({'A':[5,6],'C':[7,8]})
result=pd.concat([df1,df2],sort=True)
result

   A    B    C
0  1  3.0  NaN
1  2  4.0  NaN
0  5  NaN  7.0
1  6  NaN  8.0

### merge() function

In [106]:
df1=pd.DataFrame({
    "employee":["A","B","C"],
    "Department":["IT","HR","Finance"]
})
df2=pd.DataFrame({
    "employee":["A","B","D"],
    "Salary":[50000,40000,30000]
})
result=pd.merge(df1,df2,on="employee",how="inner")
result

  employee Department  Salary
0        A         IT   50000
1        B         HR   40000

In [107]:
result=pd.merge(df1,df2,on="employee",how="outer")
result

  employee Department   Salary
0        A         IT  50000.0
1        B         HR  40000.0
2        C    Finance      NaN
3        D        NaN  30000.0