In [1]:
import pandas as pd

In [3]:
movies=pd.read_csv("bollywood.csv",index_col="movie",squeeze=True)
print(movies)

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [4]:
movies.index

Index(['Uri: The Surgical Strike', 'Battalion 609',
       'The Accidental Prime Minister (film)', 'Why Cheat India',
       'Evening Shadows', 'Soni (film)', 'Fraud Saiyaan', 'Bombairiya',
       'Manikarnika: The Queen of Jhansi', 'Thackeray (film)',
       ...
       'Raaz (2002 film)', 'Zameen (2003 film)', 'Waisa Bhi Hota Hai Part II',
       'Devdas (2002 Hindi film)', 'Kaante', 'Hum Tumhare Hain Sanam',
       'Aankhen (2002 film)', 'Saathiya (film)', 'Company (film)',
       'Awara Paagal Deewana'],
      dtype='object', name='movie', length=1500)

In [5]:
movies.values

array(['Vicky Kaushal', 'Vicky Ahuja', 'Anupam Kher', ..., 'Vivek Oberoi',
       'Ajay Devgn', 'Akshay Kumar'], dtype=object)

In [10]:
movies[movies.values=='Akshay Kumar']

movie
Kesari (film)                           Akshay Kumar
Mission Mangal                          Akshay Kumar
Housefull 4                             Akshay Kumar
Good Newwz                              Akshay Kumar
Gold (2018 film)                        Akshay Kumar
Toilet: Ek Prem Katha                   Akshay Kumar
Airlift (film)                          Akshay Kumar
Baby (2015 Hindi film)                  Akshay Kumar
Singh Is Bliing                         Akshay Kumar
Gabbar Is Back                          Akshay Kumar
Gabbar Is Back                          Akshay Kumar
Brothers (2015 film)                    Akshay Kumar
Holiday: A Soldier Is Never Off Duty    Akshay Kumar
Entertainment (2014 film)               Akshay Kumar
The Shaukeens                           Akshay Kumar
Special 26                              Akshay Kumar
Once Upon ay Time in Mumbai Dobaara!    Akshay Kumar
Boss (2013 Hindi film)                  Akshay Kumar
Joker (2012 film)                       Akshay Kumar
Housefull 2                             Akshay Kumar
Thank You (2011 film)                   Akshay Kumar
Desi Boyz                               Akshay Kumar
Housefull (2010 film)                   Akshay Kumar
Khatta Meetha (2010 film)               Akshay Kumar
Tees Maar Khan (2010 film)              Akshay Kumar
Action Replayy                          Akshay Kumar
Blue (2009 film)                        Akshay Kumar
De Dana Dan                             Akshay Kumar
Singh Is Kinng                          Akshay Kumar
Tashan (film)                           Akshay Kumar
Bhool Bhulaiyaa                         Akshay Kumar
Namastey London                         Akshay Kumar
Welcome (2007 film)                     Akshay Kumar
Bhagam Bhag                             Akshay Kumar
Humko Deewana Kar Gaye                  Akshay Kumar
Phir Hera Pheri                         Akshay Kumar
Mere Jeevan Saathi (2006 film)          Akshay Kumar
Deewane Huye Paagal                     Akshay Kumar
Dosti: Friends Forever                  Akshay Kumar
Garam Masala (2005 film)                Akshay Kumar
Insan                                   Akshay Kumar
Aitraaz                                 Akshay Kumar
Hatya (2004 film)                       Akshay Kumar
Meri Biwi Ka Jawaab Nahin               Akshay Kumar
Police Force: An Inside Story           Akshay Kumar
Andaaz                                  Akshay Kumar
Andaaz                                  Akshay Kumar
Awara Paagal Deewana                    Akshay Kumar
Name: lead, dtype: object

In [11]:
movies[movies.values=='Akshay Kumar'].size

48

In [12]:
movies.value_counts()

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Shashank Arora       1
Preity Zinta         1
Sasha Aagha          1
Jimmy Sharma         1
Naveen Bawa          1
Name: lead, Length: 566, dtype: int64

In [13]:
x=movies.value_counts()
x[x>20]

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: lead, dtype: int64

In [15]:
marks={'ram':55,'shyam':60,'seeta':65,'geeta':70}
marks_series=pd.Series(marks,name='student result')
print(marks_series)

ram      55
shyam    60
seeta    65
geeta    70
Name: student result, dtype: int64

In [16]:
list(marks_series)

[55, 60, 65, 70]

In [17]:
dict(marks_series)

{'ram': 55, 'shyam': 60, 'seeta': 65, 'geeta': 70}

In [19]:
marks_series[1]=100
marks_series

ram       55
shyam    100
seeta     65
geeta     70
Name: student result, dtype: int64

In [21]:
100+marks_series

ram      155
shyam    200
seeta    165
geeta    170
Name: student result, dtype: int64

In [22]:
marks_series

ram       55
shyam    100
seeta     65
geeta     70
Name: student result, dtype: int64

In [25]:
a=pd.Series([2,4,6,8,10])
b=pd.Series([1,3,5,7,10])
print(a+b)

0     3
1     7
2    11
3    15
4    20
dtype: int64

In [26]:
print(a-b)

0    1
1    1
2    1
3    1
4    0
dtype: int64

In [27]:
print(a*b)

0      2
1     12
2     30
3     56
4    100
dtype: int64

# Data Frame

Pandas Dataframe is a 2-dimensional data structure like a 2 dimensional array or a table with rows and columns

In [29]:
data={'calories':[400,420,380,390],"duration":[50,40,45,60]}
df=pd.DataFrame(data)
df

   calories  duration
0       400        50
1       420        40
2       380        45
3       390        60

In [30]:
df.loc[0]

calories    400
duration     50
Name: 0, dtype: int64

In [31]:
df.iloc[0]

calories    400
duration     50
Name: 0, dtype: int64

In [34]:
df=pd.DataFrame(data,index=['day1','day2','day3','day4'])

      calories  duration
day1       400        50
day2       420        40
day3       380        45
day4       390        60

In [38]:
df.loc['day1']

calories    400
duration     50
Name: day1, dtype: int64

In [39]:
df.iloc['day1']

TypeError: Cannot index by location index with a non-integer key

In [40]:
df[::2]

      calories  duration
day1       400        50
day3       380        45

In [42]:
data={'Name':['Alice','Bob','Charlie'],'Age':[25,30,35],'city':['New York','Los angeles','Chicago']}
df=pd.DataFrame(data)
df

      Name  Age         city
0    Alice   25     New York
1      Bob   30  Los angeles
2  Charlie   35      Chicago

In [43]:
df.loc[0:2]

    Name  Age         city
0  Alice   25     New York
1    Bob   30  Los angeles

In [45]:
df.iloc[0:2]

    Name  Age         city
0  Alice   25     New York
1    Bob   30  Los angeles

In [49]:
data={'A':[1,2,3,4],'B':[5,6,7,8]}
df=pd.DataFrame(data,index=['row1','row2','row3','row4'])
df

      A  B
row1  1  5
row2  2  6
row3  3  7
row4  4  8

In [51]:
df.loc['row':'row4','B']=99
df

      A   B
row1  1  99
row2  2  99
row3  3  99
row4  4  99

In [53]:
df.iloc[1:3,0]=0
df

      A   B
row1  1  99
row2  0  99
row3  0  99
row4  4  99

In [56]:
df['C']=[10,20,30,40]
df

      A   B   C
row1  1  99  10
row2  0  99  20
row3  0  99  30
row4  4  99  40

In [57]:
df.loc[df['A']==0,'new_col']='zero'
df

      A   B   C new_col
row1  1  99  10     NaN
row2  0  99  20    zero
row3  0  99  30    zero
row4  4  99  40     NaN

In [61]:
df.loc['row5']=[10,20,30,40]
df

       A   B   C new_col
row1   1  99  10     NaN
row2   0  99  20    zero
row3   0  99  30    zero
row4   4  99  40     NaN
4     10  20  30      40
5     10  20  30      40
row5  10  20  30      40

# Set_index()

Used to set one or more columns of a dataframe as the index

In [63]:
data={'Name':['Alice','Bob','Charlie'],'Age':[25,30,35],'city':['Ny','LA','Chicago']}
df=pd.DataFrame(data)
df

      Name  Age     city
0    Alice   25       Ny
1      Bob   30       LA
2  Charlie   35  Chicago

In [66]:
df.set_index('Name',drop=False)

            Name  Age     city
Name
Alice      Alice   25       Ny
Bob          Bob   30       LA
Charlie  Charlie   35  Chicago

In [67]:
df

      Name  Age     city
0    Alice   25       Ny
1      Bob   30       LA
2  Charlie   35  Chicago

In [70]:
df.set_index(['Name','Age'],drop=False,inplace=True)
df

                Name  Age     city
Name    Age
Alice   25     Alice   25       Ny
Bob     30       Bob   30       LA
Charlie 35   Charlie   35  Chicago

# reset_index()
Used to manage and reset the index od a DataFrame

In [73]:
data={'Name':['Alice','Bob','Charlie'],'Age':[25,30,35],'city':['Ny','LA','Chicago']}
df=pd.DataFrame(data,index=['a','b','c'])
df

      Name  Age     city
a    Alice   25       Ny
b      Bob   30       LA
c  Charlie   35  Chicago

In [74]:
df_reset=df.reset_index()
df_reset

  index     Name  Age     city
0     a    Alice   25       Ny
1     b      Bob   30       LA
2     c  Charlie   35  Chicago

# DataFrame Attributes

In [75]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [77]:
df.columns

Index(['Name', 'Age', 'city'], dtype='object')

In [78]:
df.size

9

In [79]:
df.values

array([['Alice', 25, 'Ny'],
       ['Bob', 30, 'LA'],
       ['Charlie', 35, 'Chicago']], dtype=object)

In [80]:
df.dtypes

Name    object
Age      int64
city    object
dtype: object

In [82]:
df.ndim

2

In [83]:
df.shape

(3, 3)

In [85]:
df=pd.read_csv("auto-mpg.csv")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [87]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino