In [1]:
import pandas as pd

In [3]:
#to merge if both the names are different then this method is used
a1=pd.DataFrame({"id":[1,2,3],
                "name":["amit","riya","john"]})
a2=pd.DataFrame({"s_id":[1,2,4],"marks":[85,90,75]})
r=pd.merge(a1,a2,left_on="id",right_on="s_id")
print(r)

   id  name  s_id  marks
0   1  amit     1     85
1   2  riya     2     90

In [6]:
d1=pd.DataFrame({"Physics":[70,80,90]},index=[101,102,103])
d2=pd.DataFrame({"Name":["Alice","bob","charlie"]},index=[101,102,103])
r=pd.merge(d1,d2,left_index=True,right_index=True)
print(r)

     Physics     Name
101       70    Alice
102       80      bob
103       90  charlie

In [7]:
a1=pd.DataFrame({"id":[1,2,3],
                "name":["amit","riya","john"]})
a2=pd.DataFrame({"Score":[90,80,70]},index=[1,2,3])
r=pd.merge(a1,a2,left_on="id",right_index=True)
print(r)

   id  name  Score
0   1  amit     90
1   2  riya     80
2   3  john     70

###  groupby()

In [9]:
data={'product category':['Electronics','Furniture','Electronics','Furniture'],'sales':[200,150,300,100]}
df=pd.DataFrame(data)
df

  product category  sales
0      Electronics    200
1        Furniture    150
2      Electronics    300
3        Furniture    100

In [11]:
r=df.groupby("product category")['sales'].sum()
print(r)

product category
Electronics    500
Furniture      250
Name: sales, dtype: int64

In [12]:
r=df.groupby("product category")['sales'].mean()
print(r)

product category
Electronics    250
Furniture      125
Name: sales, dtype: int64

In [13]:
r=df.groupby("product category")['sales'].median()
print(r)

product category
Electronics    250
Furniture      125
Name: sales, dtype: int64

In [14]:
r=df.groupby("product category")['sales'].describe()
print(r)

                  count   mean        std    min    25%    50%    75%    max
product category
Electronics         2.0  250.0  70.710678  200.0  225.0  250.0  275.0  300.0
Furniture           2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0

In [17]:
r=df.groupby("product category")['sales'].sample()
print(r)

0    200
1    150
Name: sales, dtype: int64

In [18]:
r=df.groupby("product category")['sales'].size()
print(r)

product category
Electronics    2
Furniture      2
Name: sales, dtype: int64

In [20]:
r=df.groupby("product category")['sales'].groups
print(r)

{'Electronics': [0, 2], 'Furniture': [1, 3]}

In [21]:
r=df.groupby("product category")['sales'].nunique()
print(r)

product category
Electronics    2
Furniture      2
Name: sales, dtype: int64

In [22]:
r=df.groupby("product category")['sales'].nth(0)
print(r)

product category
Electronics    200
Furniture      150
Name: sales, dtype: int64

In [23]:
r=df.groupby("product category")['sales'].nth(1)
print(r)

product category
Electronics    300
Furniture      100
Name: sales, dtype: int64

In [24]:
r=df.groupby("product category",axis=0,as_index=True,sort=True)['sales'].count()
print(r)

product category
Electronics    2
Furniture      2
Name: sales, dtype: int64

In [25]:
r=df.groupby("product category",axis=0,as_index=False,sort=True)['sales'].count()
print(r)

  product category  sales
0      Electronics      2
1        Furniture      2

In [26]:
df=pd.DataFrame({'Region':['east','east','west','west','east','west'],
                "sales":[100,150,200,120,110,130],
                "manager":['a','b','c','d','e','f']})
df

  Region  sales manager
0   east    100       a
1   east    150       b
2   west    200       c
3   west    120       d
4   east    110       e
5   west    130       f

In [28]:
def sales_range(group):
    return group['sales'].max()-group['sales'].min() #max-min
sales=df.groupby("Region").apply(sales_range)
print(sales)

Region
east    50
west    80
dtype: int64

In [29]:
df=pd.DataFrame({"Dept":['sales','sales','HR','HR','IT','IT'],
                "Sales":[50000,60000,40000,45000,70000,75000],
                "Bonus":[5000,6000,2000,2500,8000,8500]})
r=df.groupby('Dept').agg('mean')
print(r)

       Sales  Bonus
Dept
HR     42500   2250
IT     72500   8250
sales  55000   5500

In [30]:
df=pd.DataFrame({"Dept":['sales','sales','HR','HR','IT','IT'],
                "Sales":[50000,60000,40000,45000,70000,75000],
                "Bonus":[5000,6000,2000,2500,8000,8500]})
r=df.groupby('Dept').agg(['mean','min','max'])
print(r)

       Sales               Bonus
        mean    min    max  mean   min   max
Dept
HR     42500  40000  45000  2250  2000  2500
IT     72500  70000  75000  8250  8000  8500
sales  55000  50000  60000  5500  5000  6000

In [33]:
df=pd.DataFrame({"Dept":['sales','sales','HR','HR','IT','IT'],
                "Salary":[50000,60000,40000,45000,70000,75000],
                "Bonus":[5000,6000,2000,2500,8000,8500]})
r=df.groupby('Dept').agg({'Salary':['mean','max'],"Bonus":'sum'})
print(r)

      Salary         Bonus
        mean    max    sum
Dept
HR     42500  45000   4500
IT     72500  75000  16500
sales  55000  60000  11000

In [36]:
df=pd.DataFrame({"Dept":['sales','sales','HR','HR','IT','IT'],
                "Salary":[50000,60000,40000,45000,70000,75000],
                "Bonus":[5000,6000,2000,2500,8000,8500]})
r=df.groupby('Dept').agg(MeanSalary=("Salary","mean"),MaxSalary=('Salary','max'),TotalBonus=('Bonus','sum'))
print(r)

       MeanSalary  MaxSalary  TotalBonus
Dept
HR          42500      45000        4500
IT          72500      75000       16500
sales       55000      60000       11000